### ISSUE TITLE
Is it possible to connect a SAP B1 server from a remote server with this code?

### ISSUE THREAD

**Issue by samuelj90** [rafalrozmus/java-and-sap-business-one#2]
I had a business requirement to fetch some data from SAP B1.
I would like to know is it possible to fetch the data from the SAP B1 to a remote server using the code in this repository.
When i tried to connect from my local machine it threw  `com.sap.smb.sbo.wrapper.com.ComFailException: Can't find moniker`

**Comment by rafalrozmus** [comment]
Hi Samuel,

In theory my code should work with remote connections. However, there's a
few things that need to be set up first. The SQL server needs to be
configured to accept remote connections and you'd need to open SQL server
ports and SAP license server ports to the outside world, either by having
static IP address on the SAP server or by using some sort of port
forwarding on the firewall.

Other way, would be to create a VPN connection to the remote server from
the client.

I hope that helps.



pt., 24 maj 2019 o 12:19 SAMUEL J MATHEW <notifications@github.com>
napisał(a):

**Comment by samuelj90** [comment]
Thanks for your response.
I have remote SQL connections to SAP database and also the license server is open to my server with a VPN connection but the follwing line in the code 

`company = SBOCOMUtil.newCompany();`

threw error 

`com.sap.smb.sbo.wrapper.com.ComFailException: Can't find moniker`

Can you guide me in any possible reasons for this issue?

**Comment by rafalrozmus** [comment]
Hi,

First, uninstall all SAP DI API versions from your machine and remove the
SAP DI API folders from Program Files. If you use 64-bit JDK, install
64-bit DI API. If you use 32-bit JDK, install 32-bit DI API. Don’t put both
32 and 64-bit DI API on same machine. For some reason it creates problems.

You can also try adding the path to your Java libraries in the project’s VM
Options:
-Djava.library.path=”C:\Program Files\SAP\SAP Business One DI API\JCO\LIB”

I’m not 100% sure that it’s going to solve your problem, but it’s worth
trying

czw., 30 maj 2019 o 07:11 SAMUEL J MATHEW <notifications@github.com>
napisał(a):

**Comment by samuelj90** [comment]
I currently not working in the project which I used this library so closing this issue
